name: semgrep_settings

base_config: auto

include_options:
  - r/full
# - auto

include_dir:
  - .

exclude_dir:
  - example
  - tests

exclude_rules:
  - javascript.lang.security.audit.eval-detected
  - javascript.lang.security.audit.command-injection
